# Generated by Django 3.2.5 on 2021-11-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField()),
                ('details', models.TextField()),
                ('level', models.TextField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'health_status',
            },
        ),
    ]
